#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean
m4 system/blockMeshDict.m4 > system/blockMeshDict
blockMesh
application=`getApplication`

runApplication $application 
#------------------------------------------------------------------------------
